#!/bin/bash

cd ./cmake-build-debug/

rm report
touch report

cd .. 
cd ./tests

for test in ./*.sh
 do 
 exec 3>&1 1>> /dev/null
 exec 4>&2 2>> /dev/null
 ../cmake-build-debug/UDBMS< ./fast_drop
 exec 1>&3
 exec 2>&4
status=$($test)
if [ $status -eq 0 ]
then
	echo $(basename -- "$test") 'set of tests completed' >> ../cmake-build-debug/report
	echo '' >> ../cmake-build-debug/report
fi
 done
 
 echo 'Testing finished'
