#!/bin/bash

cd ./cmake-build-debug/

rm report
touch report

cd .. 
cd ./tests

test_cnt=0

for test in $(./*)
 do 
 if [ $test -eq 0 ]
then
	test_cnt=$(( $test_cnt + 1))
	echo $test_cnt'st set of tests completed' 
	echo '' >> ../cmake-build-debug/report
fi
 done
 
 echo 'Testing finished'


