#!/bin/bash

#../cmake-build-debug/UDBMS &

sleep 3
 exec 3>&1 1>> /dev/null
 exec 2>> buffer
 #./cmake-build-debug/UDBMS_CLIENT

#touch buffer
 
 for ((i = 0; i < 10; i++))
 do
 	cmake-build-debug/UDBMS_CLIENT &
 done
 a= wc -l buffer
 echo $a
  #exec 2>&4
  exec 1>&3
  
#rm buffer
 
sleep 5
fg 1
^C
$
 if (( $a == 0 )); then
 echo 'Testing finished'
 fi
